<?php
// auto-generated by sfSimpleYamlConfigHandler
// date: 2013/05/06 02:03:14
return array (
  'invite_mode' => 
  array (
    'Default' => 1,
  ),
  'enable_mobile' => 
  array (
    'Default' => 1,
  ),
  'enable_pc' => 
  array (
    'Default' => 1,
  ),
  'self_invite_action' => 
  array (
    'Default' => 'opAuthMailAddress/requestRegisterURL',
  ),
  'help_login_error_action' => 
  array (
    'Name' => 'self_invite_action',
    'Caption' => '',
    'FormType' => '',
    'ValueType' => '',
    'IsConfig' => false,
    'IsRequired' => false,
    'Default' => 'opAuthMailAddress/helpLoginError',
  ),
  'auth_mode_caption' => 
  array (
    'IsConfig' => 0,
    'Default' => 'E-mail Address Login',
  ),
);
