<?php
// auto-generated by sfSimpleYamlConfigHandler
// date: 2013/05/06 02:03:14
return array (
  'layoutA' => 
  array (
    0 => 'top',
    1 => 'sideMenu',
    2 => 'contents',
    3 => 'bottom',
  ),
  'layoutB' => 
  array (
    0 => 'sideMenu',
    1 => 'contents',
    2 => 'bottom',
  ),
  'layoutC' => 
  array (
    0 => 'contents',
    1 => 'bottom',
  ),
  'layoutD' => 
  array (
    0 => 'contents',
  ),
  'layoutE' => 
  array (
    0 => 'top',
    1 => 'contents',
    2 => 'bottom',
  ),
);
