<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/05/06 02:03:14

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=symfonycms;host=localhost;port=80',
  'username' => 'root',
  'encoding' => 'utf8',
  'attributes' => 
  array (
    164 => true,
  ),
  'password' => '123456',
  'name' => 'doctrine',
)),);
