<?php
// auto-generated by sfSimpleYamlConfigHandler
// date: 2013/05/06 02:03:14
return array (
  'gadget' => 
  array (
    'name' => 'ホーム画面',
    'layout' => 
    array (
      'default' => 'layoutA',
      'choices' => 
      array (
        0 => 'layoutA',
        1 => 'layoutB',
        2 => 'layoutC',
      ),
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'homeGadgetPlot',
    ),
  ),
  'profile' => 
  array (
    'name' => 'プロフィール画面',
    'layout' => 
    array (
      'default' => 'layoutA',
      'choices' => 
      array (
        0 => 'layoutA',
        1 => 'layoutB',
        2 => 'layoutC',
      ),
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'profileGadgetPlot',
    ),
  ),
  'login' => 
  array (
    'name' => 'ログイン画面',
    'layout' => 
    array (
      'default' => 'layoutA',
      'choices' => 
      array (
        0 => 'layoutA',
        1 => 'layoutB',
        2 => 'layoutC',
      ),
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'loginGadgetPlot',
    ),
  ),
  'sideBanner' => 
  array (
    'name' => 'サイドバナー',
    'layout' => 
    array (
      'default' => 'layoutD',
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'sideBannerGadgetPlot',
    ),
  ),
  'mobile' => 
  array (
    'name' => '携帯版ホーム画面',
    'layout' => 
    array (
      'default' => 'layoutE',
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'mobileHomeGadgetPlot',
    ),
  ),
  'mobileProfile' => 
  array (
    'name' => '携帯版プロフィール画面',
    'layout' => 
    array (
      'default' => 'layoutE',
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'mobileProfileGadgetPlot',
    ),
  ),
  'mobileLogin' => 
  array (
    'name' => '携帯版ログイン画面',
    'layout' => 
    array (
      'default' => 'layoutD',
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'mobileLoginGadgetPlot',
    ),
  ),
  'mobileHeader' => 
  array (
    'name' => '携帯版ヘッダー',
    'layout' => 
    array (
      'default' => 'layoutD',
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'mobileHeaderGadgetPlot',
    ),
  ),
  'mobileFooter' => 
  array (
    'name' => '携帯版フッター',
    'layout' => 
    array (
      'default' => 'layoutD',
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'mobileFooterGadgetPlot',
    ),
  ),
  'smartphone' => 
  array (
    'name' => 'スマートフォン版ホーム画面',
    'layout' => 
    array (
      'default' => 'layoutD',
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'smartphoneHomeGadgetPlot',
    ),
  ),
  'smartphoneProfile' => 
  array (
    'name' => 'スマートフォン版プロフィール画面',
    'layout' => 
    array (
      'default' => 'layoutD',
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'smartphoneProfileGadgetPlot',
    ),
  ),
  'smartphoneCommunity' => 
  array (
    'name' => 'スマートフォン版コミュニティ画面',
    'layout' => 
    array (
      'default' => 'layoutD',
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'smartphoneCommunityGadgetPlot',
    ),
  ),
  'smartphoneLogin' => 
  array (
    'name' => 'スマートフォン版ログイン画面',
    'layout' => 
    array (
      'default' => 'layoutD',
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'smartphoneLoginGadgetPlot',
    ),
  ),
  'smartphoneFooter' => 
  array (
    'name' => 'スマートフォン版フッター',
    'layout' => 
    array (
      'default' => 'layoutD',
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'smartphoneFooterGadgetPlot',
    ),
  ),
  'dailyNews' => 
  array (
    'name' => 'デイリーニュース（PCメールアドレス向け）',
    'layout' => 
    array (
      'default' => 'layoutD',
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'dailyNewsGadgetPlot',
    ),
  ),
  'mobileDailyNews' => 
  array (
    'name' => 'デイリーニュース（携帯メールアドレス向け）',
    'layout' => 
    array (
      'default' => 'layoutD',
    ),
    'plot_action' => 
    array (
      0 => 'design',
      1 => 'mobileDailyNewsGadgetPlot',
    ),
  ),
);
