<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/05/06 02:03:15
sfConfig::add(array(
  'mod_friend_enabled' => true,
  'mod_friend_view_class' => 'op',
  'mod_friend_default_nav' => 'friend',
));
