<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/05/06 02:03:15
sfConfig::add(array(
  'mod_community_enabled' => true,
  'mod_community_view_class' => 'op',
  'mod_community_default_nav' => 'community',
  'mod_community_nav_list' => 'default',
  'mod_community_nav_joinlist' => 'default',
));
