<?php
// auto-generated by opSecurityConfigHandler
// date: 2013/05/06 02:03:58
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'SNSMember',
  ),
  'home' => 
  array (
    'is_secure' => false,
  ),
  'memberlist' => 
  array (
    'is_secure' => false,
  ),
);
