<?php
// auto-generated by opSecurityConfigHandler
// date: 2013/05/06 02:03:14
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'SNSMember',
  ),
  'register' => 
  array (
    'is_secure' => false,
  ),
  'registerinput' => 
  array (
    'is_secure' => false,
  ),
  'configcomplete' => 
  array (
    'is_secure' => false,
  ),
  'changelanguage' => 
  array (
    'is_secure' => false,
  ),
  'registermobiletoregisterend' => 
  array (
    'is_secure' => false,
  ),
  'registermobiletoregisterendfinish' => 
  array (
    'is_secure' => false,
  ),
  'profile' => 
  array (
    'is_secure' => $this->getUser()->isAuthenticated(),
  ),
  'smtprofile' => 
  array (
    'is_secure' => $this->getUser()->isAuthenticated(),
  ),
);
